name: Deploy Docker Image from Artifact Registry to Cloud Run

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Push to Artifact Registry"]
    types:
      - completed

jobs:
  deploy_docker:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"
          project_id: ${{ vars.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Docker auth
        run: |
          gcloud auth configure-docker ${{ vars.ARTIFACT_REGION }}-docker.pkg.dev --quiet

      - name: Verify image exists
        run: |
          if ! gcloud artifacts docker images describe \
            ${{ vars.ARTIFACT_REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.ARTIFACT_REGISTRY }}/${{ vars.IMAGE_NAME }}:latest; then
            echo "❌ Docker image not found in Artifact Registry"
            exit 1
          fi
          echo "✅ Docker image verified in Artifact Registry"

      - name: Deploy to Cloud Run
        run: |
          echo "🚀 Deploying to Cloud Run..."
          gcloud run deploy ${{ vars.SERVICE_NAME || 'beets-vs-weeds-api-prod' }} \
            --image ${{ vars.ARTIFACT_REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.ARTIFACT_REGISTRY }}/${{ vars.IMAGE_NAME }}:latest \
            --region ${{ vars.ARTIFACT_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            --set-env-vars="DATA_SIZE=${{ vars.DATA_SIZE || 'all' }},CHUNK_SIZE=${{ vars.CHUNK_SIZE || 200 }},FILE_ORIGIN=gcp,MODEL_TARGET=gcs,GCP_PROJECT=${{ vars.PROJECT_ID }},GCP_REGION=${{ vars.ARTIFACT_REGION }},BUCKET_NAME=${{ vars.BUCKET_NAME || 'beets_vs_weeds' }},RESIZED=${{ vars.RESIZED || '256' }}" \
            --memory=12Gi \
            --cpu=4 \
            --max-instances=10 \
            --timeout=3600 \
            --concurrency=80

      - name: Get deployment details
        run: |
          SERVICE_URL=$(gcloud run services describe ${{ vars.SERVICE_NAME || 'beets-vs-weeds-api-prod' }} \
            --region=${{ vars.ARTIFACT_REGION }} \
            --format='value(status.url)')

          echo "🎉 Application deployed successfully to Cloud Run!"
          echo "📍 Service: ${{ vars.SERVICE_NAME || 'beets-vs-weeds-api-prod' }}"
          echo "🌍 Region: ${{ vars.ARTIFACT_REGION }}"
          echo "🌐 Service URL: $SERVICE_URL"
